name: Semantic Release

on:
  # Runs on pushes targeting the `main` branch. Change this to `master` if you're
  # using the `master` branch as the default branch.
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release version

    # Specifies the operating system for the job to run on.
    runs-on: ubuntu-latest

    steps:
      # Step to check out the repository code.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to set up Node.js.
      - id: setup-node
        uses: actions/setup-node@v4
        with:
           node-version: 22

      # Step to cache the `node_modules` directory to improve performance of subsequent runs.
      - name: Cache Node modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Step to install dependencies using Yarn.
      - name: Install dependencies
        run: yarn

      # Step to build the project (production build).
      - name: Run Build
        run: yarn build:prod

      # Authentication with Google Cloud via Service Accounts.
      - id: 'auth_google_cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Uploading a schema file to Google Cloud Storage.
      - name: Upload schema to Google Cloud Storage
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'public/commit-jazzer-schema.json' # Local path to the file you want to download.
          destination: 'commit-jazzer' # The path inside the GCC package.

      # Step to run Semantic Release.
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Passes GitHub token for authentication with GitHub API.
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Passes NPM token for publishing to NPM.
