name: Integration

on:
  # Trigger the workflow on pull requests targeting the `main` branch.
  pull_request:
    branches: [main]

# Sets permissions for the GITHUB_TOKEN. This grants read access to the repository contents.
permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # This defines the Node.js versions to run the tests on.
        # The tests will run in parallel for each of these Node versions.
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      # Step to check out the repository code.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to cache the `node_modules` directory to improve performance of subsequent runs.
      - name: Cache Node modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

        # Step to set up Node.js with the version from the matrix.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

        # Step to install dependencies using Yarn.
      - name: Install dependencies
        run: yarn

  # Step to run ESLint checks on the codebase.
  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Eslint checks
        run: yarn lint:check

  # Step to run spell checking on the codebase.
  spell:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Spell checks
        run: yarn cspell

  # Step to run tests on the codebase.
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: yarn test

  # Step to build the project for production.
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: yarn build:prod
